create table if not exists public.print_records (
  id bigint generated by default as identity primary key,
  print_date date not null,
  requester text not null,
  sector text not null,
  segment text not null,
  material text not null,
  page_size text not null default 'A4',
  pages_per_copy integer not null check (pages_per_copy > 0),
  copies integer not null check (copies > 0),
  print_mode text not null check (print_mode in ('simplex', 'duplex')),
  printed_faces integer not null,
  sheets_used integer not null,
  authorized boolean not null default true,
  operator text not null check (operator in ('Marcos Gabriel', 'Everton Douglas')),
  notes text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_print_records_print_date on public.print_records (print_date desc);
alter table public.print_records enable row level security;
